### ISSUE TITLE
add borsh support of serialize/deserialze behind borsh gate (solana, no_std)

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ergoplatform/bounded-vec#14]

**Comment by greenhat** [comment]
Could you please elaborate? What is the borsh and why bounded-vec should support it.

**Comment by dzmitry-lahoda** [comment]
https://borsh.io/ , it is serde . serde is feature in route crate

**Comment by dzmitry-lahoda** [comment]
will add when ported to solana/near

**Comment by dzmitry-lahoda** [comment]
fixed https://github.com/ergoplatform/bounded-vec/pull/28
